accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^login/$',  views.login),
    url(r'^logout/$',  views.logout), 
    url(r'^register/$',  views.register),
    url(r'^index/$',  views.index),
    url(r'^home/$',  views.home),
)

music_recommed_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'music_recommed_system.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'accounts.views.login'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^mymusic/', include('mymusic.urls')),
    url(r'^social-music/', include('social_music.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': 'media/'}),
    url( r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': 'static/' }),
    url(r'^favourite/', include('favourite.urls')),
    url(r'^captcha/', include('captcha.urls')),
]

mymusic/urls.py
from django.conf.urls import patterns, url
from mymusic import views

urlpatterns = patterns('',
    url(r'^song-lib',  views.song_lib),
    url(r'^play',  views.play),
    url(r'^create-fav', views.create_fav),
    url(r'^remove-fav', views.remove_fav),
    url(r'^singer', views.singer),
    url(r'^search-singer', views.search_singer),
    url(r'^search-song', views.search_song),
    url(r'^search-prompt', views.search_prompt),
    url(r'^comment', views.comment),
    url(r'^favour-comment', views.favour_comment),
    url(r'^cancel-favour-comment', views.cancel_favour_comment),
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserMessage(models.Model):
	def __unicode__(self):
		return self.user

	user = models.ForeignKey(User)
	intro = models.CharField(max_length=255, default='')
	head = models.CharField(max_length=255, default='default')

accounts/forms.py
#coding=utf-8
from django import forms  
from django.contrib.auth.models import User 
from captcha.fields import CaptchaField
      
# 登录表单
class LoginForm(forms.Form):  
    username = forms.CharField(  
            required=True,  
            label=u"用户名",  
            error_messages={'required': '请输入用户名'},  
            widget=forms.TextInput(  
                attrs={  
                    'placeholder':u"用户名",  
                }  
            ),  
    )      
    password = forms.CharField(  
            required=True,  
            label=u"密码",  
            error_messages={'required': u'请输入密码'},  
            widget=forms.PasswordInput(  
                attrs={  
                    'placeholder':u"密码",  
                }  
            ),  
    )     
    def clean(self):  
        if not self.is_valid():  
            raise forms.ValidationError(u"用户名和密码为必填项")  
        else:  
            cleaned_data = super(LoginForm, self).clean() 

# 注册表单
class RegistForm(forms.Form):
    username = forms.CharField(
        required=True,
        label=u'用户名',
        error_messages={'required': '请输入用户名'},  
            widget=forms.TextInput(  
                attrs={  
                    'placeholder':u"用户名",  
                }  
            ),
    )  
    password = forms.CharField(  
            required=True,  
            label=u"密码",  
            error_messages={'required': u'请输入密码'},  
            widget=forms.PasswordInput(  
                attrs={  
                    'placeholder':u"密码",  
                }  
            ),  
    ) 
    password_again = forms.CharField(  
            required=True,  
            label=u"再次输入密码",  
            error_messages={'required': u'请输入密码'},  
            widget=forms.PasswordInput(  
                attrs={  
                    'placeholder':u"密码",  
                }  
            ),  
    )

    email = forms.CharField(  
            required=True,  
            label=u"邮箱地址",  
            error_messages={'required': u'请输入邮箱'},  
            widget=forms.TextInput(  
                attrs={  
                    'placeholder':u"邮箱",  
                }  
            ),  
    )

    #captcha = CaptchaField()
    
    def clean(self):  
        if not self.is_valid():  
            raise forms.ValidationError(u"请重新确认填写是否有误")  
        else:  
            cleaned_data = super(RegistForm, self).clean()

accounts/views.py
#coding=utf-8
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User    
from django.contrib import auth
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required 
from accounts.forms import LoginForm, RegistForm
from django.views.decorators.csrf import csrf_exempt
from mymusic.models import Song
from mymusic.models import Singer
from mymusic.pages_assistant import Page_Assistant
from models import UserMessage
from social_music.models import UserNews
from social_music.models import Attention
from django.core.mail import send_mail
from favourite.lastSong import getLastPlayedSong

@csrf_exempt
def register(request):
    if request.method == 'GET':
        form = RegistForm()
        return render_to_response("register.html", RequestContext(request, {'form': form}))
    else:         
        form = RegistForm(request.POST)
        register_flag = True
        username_tips = False
        password_tips = False
        email_tips = False
        tips_message = ''

        if form.is_valid():
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            password_again = request.POST.get('password_again', '')
            email = request.POST.get('email', '')
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                pass
            else:
                tips_message = u'用户名已存在'
                username_tips = True
                register_flag = False

            if register_flag == True and password != password_again:
                tips_message = u'两次密码不一致'
                password_tips = True
                register_flag = False
                
            sendEmail = dict()
            sendEmail['from'] = 'dinoshuo@163.com'
            with open('media/email/register.txt') as f:
                allEmail = f.read().split('\n')
                sendEmail['subject'] = allEmail[0]
                sendEmail['text'] = ''.join(allEmail[1:]) % username.encode('utf-8')
            
            emailReturnNo = send_mail(sendEmail['subject'], sendEmail['text'], sendEmail['from'], [email], fail_silently=False)
            if 0 == emailReturnNo:
                tips_message = u'邮箱有误'
                email_tips = True
                register_flag = False

            if register_flag:
                user = User.objects.create_user(username=username,
                                                password=password,
                                                email=email)

                user.save()
                usermessage = UserMessage()
                print type(request.user)
                usermessage.user = user
                usermessage.save()

                return HttpResponseRedirect('/accounts/login/')
            
        return render_to_response(
            'register.html',
            RequestContext(request, {'form': form,
                                     'tips': True,
                                     'tips_title': u'错误!',
                                     'tips_message': tips_message,
                                     'username_tips': username_tips,
                                     'password_tips': password_tips,
                                     'email_tips': email_tips}))


@csrf_exempt
def login(request): 
    if request.user.is_authenticated():
        return HttpResponseRedirect('/accounts/index/')
    else:
        if request.method == 'GET':  
            form = LoginForm()
            return render_to_response('login.html', RequestContext(request, {'form': form}))
        else:
            form = LoginForm(request.POST)
            if form.is_valid():
                username = request.POST.get('username', '')
                password = request.POST.get('password', '')
                user = auth.authenticate(username=username, password=password)

                if user is not None and user.is_active:
                    auth.login(request, user)
                    return HttpResponseRedirect('/accounts/index/')

            return render_to_response(
                'login.html',
                RequestContext(request, {'form': form,
                                         'tips': True,
                                         'tips_title': u'错误!',
                                         'tips_message': u'用户名或密码错误'}))


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/accounts/login/')


@login_required
def index(request):

    if request.method == 'GET':
        p = request.GET.get('p', 1)

        #将网页分页展示
        page_assistant = Page_Assistant(count=Song.objects.count(), page_size=20)
        pre_page = page_assistant.get_pre_page_no(int(p))
        cur_page = int(p)
        nex_page = page_assistant.get_nex_page_no(int(p))
        page_nums = page_assistant.get_pages_list(cur_page)
        b, e = page_assistant.get_objects_by_pageno(cur_page)
        songs = Song.objects.all()[b:e]

        #读取新消息的数量
        newsCount = UserNews.objects.filter(toUser=request.user, seen=False).count()
        
        #上一次播放的音乐
        last_song = getLastPlayedSong(request.user)
        
        return render_to_response(
            'index.html', 
            RequestContext(request, {  'last_song': last_song,
                                       'songs': songs,
                                        'user': request.user,
                                        'page_nums': page_nums,
                                        'pre_page': pre_page,
                                        'cur_page': cur_page,
                                        'nex_page': nex_page,
                                        'newsCount': newsCount}))

@login_required
def home(request):
    #访问个人主页
    if request.method == 'GET':
        id = request.GET['id']
        user = User.objects.get(pk=id)
        print "[INFO]accounts.views.home: (uid=%s, uname=%s)" %(id, user)
        try:
            usermessage = UserMessage.objects.get(user=user)
        except UserMessage.DoesNotExist:
            print "[ERROE]accounts.views.home: 内部错误,不存在的UserMessage"

        try:
            Attention.objects.get(user=request.user, attendedUser=user)
            isFollow = True
        except Attention.DoesNotExist:
            isFollow = False

        #读取新消息的数量
        newsCount = UserNews.objects.filter(toUser=request.user, seen=False).count()
        
        #上一次播放的音乐
        last_song = getLastPlayedSong(request.user)
        
        return render_to_response(
                'home.html', 
                RequestContext(request, {   'last_song': last_song,
                                            'isFollow': isFollow,
                                            'theuser': user,
                                            'head': usermessage.head,
                                            'intro': usermessage.intro,
                                            'newsCount': newsCount}))

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.css.map">
    
    <link href="{{ STATIC_URL }}Flat-UI-master/dist/css/vendor/bootstrap.min.css" rel="stylesheet">
    <!-- Loading Flat UI -->
    <link href="{{ STATIC_URL }}Flat-UI-master/dist/css/flat-ui.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block cdn %}
    {% endblock %}
  </head>
  <body>
    <style type="text/css">
      .ge-player-simple {
        max-width: 100%;
        background-color: black;
        color: white;
      }
      .progress {
        height: 2px;
        top: 0;
      }
      #bottom {
        width: 100%;
        min-height: 36px;
        background-color: #262626; 
        opacity: 0.85; 
        position: fixed;
        bottom: 0px;
        _position: absolute;
        _top: expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight));
      }
    </style>
    <script src= "{{ STATIC_URL }}js/search.js"></script>
    <script src= "{{ STATIC_URL }}h5player/dist/player-with-css.min.js"></script>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/accounts/index/">音乐推荐系统</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li {% block find %}{% endblock %}><a href="/accounts/index?p=1">发现音乐</a></li>
            </ul>
            <ul class="nav navbar-nav">
              <li {% block mine %}{% endblock %}><a href="/mymusic/song-lib/">我的音乐</a></li>
            </ul>
            <ul class="nav navbar-nav">
              <li {% block share %}{% endblock %}><a href="/social-music/share/">分享音乐</a></li>
            </ul>
            <form action="/mymusic/search-song" method="GET" class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <div class="input-group">             
                        <input type="text" name="key" class="form-control" placeholder="搜索音乐，歌手">
                        <span class="input-group-btn">
                            <button type="submit" class="btn"><span class="fui-search"></span></button>
                        </span>
                    </div>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{user}} <span class="glyphicon glyphicon-user" aria-hidden="true"></span<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/accounts/home?id={{user.id}}">我的主页</a></li>
                        <li><a href="/social-music/msg?id={{user.id}}&IsComment=1">消息中心
                          {% if newsCount != 0 %}
                          <span class="badge pull-right" style="background-color: #CD4343;">{{ newsCount }}</span>
                          {% endif %}
                        </a></li>
                        <li class="divider"></li>
                        <li><a href="/accounts/logout/">退出</a></li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="starter-template">
      <div class="container">
        {% block content %}
        {% endblock %} 
      </div>
      <div id="bottom">
        <div class="container">
          <div id="simplePlayer"></div>
        </div>
      </div>
    </div><!-- /.container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
 
    <script src="http://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script>
    {% load staticfiles %}
    var simplePlayer = new Player({
    container: document.getElementById('simplePlayer'),
      image: '{{ MEDIA_URL }}music/{{last_song.pic_link}}',
      theme: 'simple',
      classes: {
        //list: 'fa fa-list',
        prev: 'fa fa-step-backward',
        play: 'fa fa-play',
        next: 'fa fa-step-forward',
        pause: 'fa fa-pause',
      }
    });
    simplePlayer.setSongs([
    {
      name: '{{ last_song.title }}',
      url: '{{ MEDIA_URL }}music/{{last_song.song_link}}',
      artist: '{{ last_song.singer }}',
      image: '{{ MEDIA_URL }}music/{{last_song.pic_link}}',
    }
    ]);
    //simplePlayer.play(0);
  </script>
  </body>
</html>


accounts/templates/home.html
{% extends "base.html" %} 
{% block cdn %}

{% endblock %}
{% block find %}
class="active"
{% endblock %}

{% block content %} 
<script src= "{{ STATIC_URL }}js/xmlhttp.js"></script>
<script src= "{{ STATIC_URL }}js/home.js"></script>
<div class="row">
  <div class="col-xs-12 col-md-8">
  	<div class="row">
  		<div class="col-xs-6 col-md-3">
    		<a href="#" class="thumbnail">
          <img src="{{ MEDIA_URL }}heads/{{head}}_large" alt="...">
        </a>  
  		</div>
  		<div class="page-header">
  			<h3>{{theuser}}</h3>
        {% ifnotequal user theuser %}
          {% ifequal isFollow False %}
          <a class="btn btn-primary" onclick="change({{theuser.id}})" id="focus" href="javascript:void(0);" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>关注</a>
          {% else %}
          <a class="btn btn-primary" onclick="change({{theuser.id}})" id="focus" href="javascript:void(0);" role="button"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>取消关注</a>
          {% endifequal %}
        {% endifnotequal %}
		  </div>
			 个人介绍:{{intro}}
	 </div>
  </div>
  <div class="col-xs-6 col-md-4">

  </div>
</div>
{% endblock %}  




accounts/templates/index.html
{% extends "base.html" %} 
{% block cdn %}

{% endblock %}
{% block find %}
class="active"
{% endblock %}

{% block content %} 
<span class="icon-headphones"></span>  
<ul class="list-group">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>歌曲标题</th>
                <th>歌手</th>
                <th>其它</th>
            </tr>
        </thead>
        <tbody>
            {% for song in songs %}
            <tr>
                <th><a href="/mymusic/play?id={{song.pk}}" style="color: #34495e">{{song.title}}</a></th>
                <th><a href="/mymusic/singer?id={{song.singer.id}}" style="color: #34495e">{{song.singer.name}}</a></th>
                <th>
				    <a onclick=send_get_request({{song.pk}})><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span></a>
				</th>
            </tr>
            {% endfor %}
        <tbody>
    </table>
	<nav>
        <div class="pagination">
            <ul>
                <li class="previous">
                    <a href="/accounts/index/?p={{pre_page}}"<span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a>
                </li>
                {% for page_num in page_nums %}
				{% ifequal page_num cur_page %}
                    <li class="active"><a href="/accounts/index/?p={{page_num}}">{{ page_num }}</a></li>
                {% else %}
				    <li><a href="/accounts/index/?p={{page_num}}">{{ page_num }}</a></li>
				{% endifequal %}
				{% endfor %}
                <li class="next">
                    <a href="/accounts/index/?p={{nex_page}}"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a>
                </li>
            </ul>
        </div>
	</nav>
</ul>

<script type="text/javascript">
	var xmlhttp;

		function createxmlhttp(){

			if (window.XMLHttpRequest)
			{// code for IE7+, Firefox, Chrome, Opera, Safari
				xmlhttp=new XMLHttpRequest();
			}
			else
			{// code for IE6, IE5
				xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
			}

		}

		function addURLParam(url, name, value){
			url += (url.indexOf("?") == -1 ? "?" : "&")
			url += encodeURIComponent(name) + "=" + encodeURIComponent(value);
			return url;
		}
		
		function send_get_request(value){
			createxmlhttp();
			url = "/mymusic/create-fav";
			url = addURLParam(url, "id", value);
			xmlhttp.open("get", url, true);
			xmlhttp.send();
		}
</script>
{% endblock %}  

accounts/templates/login.html

{% extends "base.html" %} 
{% block cdn %}

{% endblock %}

{% block content %} 
    <div class="starter-template">
        <div class="container">
        <style type="text/css">
        body{ 
            background: url({{ MEDIA_URL }}pictures/20100723153502478.jpg)no-repeat;
            background-size:cover; 
        }
        .hub-overlay {
            width: 400px;
            margin-left: 20px;
            margin-top: 80px;
            margin-bottom: 80px;
            background-color: rgba(36,50,55,0.4);
            border-radius: 4px;
            padding: 30px 40px;
            padding-bottom: 40px;
            color: rgba(255,255,255,0.8);
        }
        </style>
            <div class="row">
                <div class="col-xs-12 col-md-8">
                </div>
                <div class="col-xs-6 col-md-4">
                    <div class="hub-overlay">
                        <h3>登录音乐推荐系统</h3>
                        <form class="hub-signup-form" method="post" action="">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
                                    <input class="form-control" id="id_username" maxlength="30" name="username" placeholder="Username" type="text" />
                                </div>
                                
                            </div>
                            <div class="form-group">
                                <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></div>
                                    <input class="form-control" id="id_password" maxlength="30" name="password" placeholder="Password" type="password" />
                                </div>
                                {% if tips %}
                                <strong>{{tips_title}}</strong>
                                {{tips_message}}
                                {% endif %}
                            </div>
                            <button class="btn btn-primary btn-block" type="submit">登录</button>
                            <a href="/accounts/register/"><input type="button" value="注册" class="btn btn-success btn-block"></a>
                        </form>
                    </div>
                </div>
            </div> 
        </div>
    </div>      
        </div>
    </div><!-- /.container -->
{% endblock %} 

accounts/templates/register.html
{% extends "base.html" %} 
{% block cdn %}

{% endblock %}

{% block content %}
    <div class="starter-template">
      <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                
                <div class="hub-overlay">
                    <h2>个人信息</h2>
                    <form class="form-horizontal" action="" method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
                                <input class="form-control" id="id_username" maxlength="30" name="username" placeholder="Username" type="text" />
                            </div>
                            {% if username_tips %}
                            <strong>{{tips_title}}</strong>
                            {{tips_message}}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></div>
                                <input class="form-control" id="id_password" maxlength="30" name="password" placeholder="Password" type="password" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></div>
                                <input class="form-control" id="id_password_again" maxlength="30" name="password_again" placeholder="Password Again" type="password" />
                            </div>
                            {% if password_tips %}
                            <strong>{{tips_title}}</strong>
                            {{tips_message}}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></div>
                                <input class="form-control" id="id_email" maxlength="30" name="email" placeholder="Email" type="email" />
                            </div>
                            {% if email_tips %}
                            <strong>{{tips_title}}</strong>
                            {{tips_message}}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                {{form.captcha}}
                            {% if email_tips %}
                            <strong>{{tips_title}}</strong>
                            {{tips_message}}
                            {% endif %}
                        </div>
                        <button class="btn btn-block btn-primary" type="submit">注册</button>
                    </form>
                </div>
            </div>
            <div class="col-md-2"></div>
      </div>
    </div>
{% endblock %}

